source: src
host: 0.0.0.0

exclude:
  - .idea
  - package.json

defaults:
  - scope:
      type: "icons"
    values:
      layout: icon
      in-bg: true
      permalink: 'icons/:slug'

collections:
  icons:
    output: true
