plugins:
  - jekyll-last-modified-at

exclude:
  - .idea
  - package.json

defaults:
  - scope:
      type: "icons"
    values:
      layout: icon
      permalink: 'icons/tabler-:slug'

collections:
  icons:
    output: true
